### ISSUE TITLE
Publish formatter library releases to jcenter/maven central

### ISSUE THREAD

**Issue by matthiasbalke** [antlr/Antlr4Formatter#14]
To embed the formatting library into other projects, it would be helpful to publish releases to jCenter or Maven Central.

I'm not sure about the standalone version. How do other Antlr projects distribute artifacts like that? We could distribute them as GitHub releases.

**Comment by teverett** [comment]
I had previously made a 1.0 release.  I can do a 1.1 now and then make the
version 1.2-SNAPSHOT, if that works?

[image: Screen Shot 2018-12-27 at 11.04.34 AM.png]

**Comment by matthiasbalke** [comment]
How about using [semantic versioning](https://semver.org) than we could release version 1.1.0 because the API is still compatible. Using semantic versioning gives finer insights to users about what was done in a release.

Where are the releases located? I checked [maven.org](https://search.maven.org/search?q=Antlr4formatter), but didn’t find version 1.0.

**Comment by teverett** [comment]
ok so what would the next version be after the release?  1.2.0-SNAPSHOT?

**Comment by matthiasbalke** [comment]
I would set the next version to 1.1.1-SNAPSHOT as it is more likely that the next version will be a bug fix. Also you can change the next version right before the next release in case this assumption was wrong.

**Comment by teverett** [comment]
done
