### ISSUE TITLE
block pull requests when build is broken

### ISSUE THREAD

**Issue by matthiasbalke** [antlr/Antlr4Formatter#18]
I think we should activate the option of the repository, that broken pull requests cannot be merged. Otherwise we have unstable included in the mainline.

What do you think @teverett?

**Comment by teverett** [comment]
We can do it, however myself and @parrt are the only people who have pull access.

**Comment by matthiasbalke** [comment]
Ok, this is comming from my daily work doing continuous delivery pipelines 😉 You never want to break your ability to release.

**Comment by teverett** [comment]
:)
