### ISSUE TITLE
public static instead of private static final

### ISSUE THREAD

**Issue by quantrpeter** [antlr/Antlr4Formatter#39]
Hi
     If changing these variables such as  "newlineBeforeRules" to "public static". I think it is much better than "private static final". Since i can modify it in runtime.
Thanks
Peter

**Comment by matthiasbalke** [comment]
@quantrpeter How about a concept for configuring the formatter as a whole? I would prefer a text configuration file that can be checked in with the project to be formatted.

**Comment by teverett** [comment]
No objections here.   A PR would be welcome.
