### ISSUE TITLE
extract antlr4 formatting into libray

### ISSUE THREAD

**Issue by matthiasbalke** [antlr/Antlr4Formatter#5]
I would like to refactor the project to split it into a library module and a standalone jar.
This way the antlr4 formatter could be embedded into other programs, but also be used as standalone formatter from CLI.

I am working on an integration of this formatter into [diffplug/spotless](https://github.com/diffplug/spotless).

If you're interested in this please let me know.

PS: I modified the current version to create a draft on how to embedd it in spotless. I'll open a PR for my current smaller changes.

**Comment by teverett** [comment]
Any PR's are welcome.  Thanks for your interest.

**Comment by matthiasbalke** [comment]
sorry I messed up my PR #6 and have to do it again :weary:

**Comment by matthiasbalke** [comment]
> Any PR's are welcome. Thanks for your interest.

I'll provide another PR to split up the formatter into library and standalone module.

**Comment by matthiasbalke** [comment]
I think my PR removed your grammar updates. I didn't realize you changed them in between my commits. Sorry. I can fix them tomorrow.

**Comment by teverett** [comment]
no big deal :)
